FROM ubuntu:focal

RUN apt-get update

RUN apt-get install -y update
# dns
RUN apt-get install dnsutils
#mail
RUN apt-get install mailutils
#voip
RUN apt-get install -y iputils-ping
#web
RUN apt-get install curl

CMD ["bash"]
